spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: security
          uri: lb://rc-security
          predicates:
            - Path=/api-security/**
          filters:
            - PreserveHostHeader
        - id: system
          uri: lb://rc-system
          predicates:
            - Path=/api-system/**
          filters:
            - PreserveHostHeader