spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: oauth2
          uri: lb://rc-oauth2
          predicates:
            - Path=/api-oauth2/**
          filters:
            - PreserveHostHeader